// This file is entirely generated by AI. I don't particularly care about the
// implementation detail nor logic of this file because it is only used on the
// sad path of a panic, which ideally never ever happens.
//
// Don't take the logic in this file as gospel. It is certainly possible that
// things in here are broken, weirdly designed, have unintentional bugs, etc. If
// something seems weird to you, feel free to nuke the old implementation and
// replace it with something that makes more sense.

const std = @import("std");
const root = @import("root");
const builtin = @import("builtin");

const SelfInfo = @This();
const Io = std.Io;
const Allocator = std.mem.Allocator;
const Symbol = std.debug.Symbol;
const SelfInfoError = std.debug.SelfInfoError;
const elf = std.elf;
const Endian = std.builtin.Endian;
const Dwarf = std.debug.Dwarf;

state: State = .uninitialized,
runtime_virtual_base: usize = 0,
elf_bytes: []const u8 = &.{},
elf_is_64: bool = false,
elf_endian: Endian = .little,
symtab: ?Symtab = null,
strtab: ?[]const u8 = null,
dwarf: ?Dwarf = null,

const State = union(enum) {
    uninitialized,
    ready,
    failed: SelfInfoError,
};

const Symtab = struct {
    entry_size: u64,
    bytes: []const u8,
};

pub const init: SelfInfo = .{};
pub const can_unwind = false;

pub fn deinit(si: *SelfInfo, io: Io) void {
    _ = io;
    if (si.dwarf) |*dwarf| {
        dwarf.deinit(std.debug.getDebugInfoAllocator());
        si.dwarf = null;
    }
}

pub fn getSymbols(
    si: *SelfInfo,
    io: Io,
    symbol_allocator: Allocator,
    text_arena: Allocator,
    address: usize,
    include_inline_callers: bool,
    symbols: *std.ArrayList(Symbol),
) SelfInfoError!void {
    _ = io;

    try si.ensureParsed();

    if (si.dwarf) |*dwarf| {
        if (si.tryDwarfGetSymbols(dwarf, symbol_allocator, text_arena, address, include_inline_callers, symbols)) return;
    }

    const strtab = si.strtab orelse return error.MissingDebugInfo;
    const symtab = si.symtab orelse return error.MissingDebugInfo;

    if (si.findSymbol(strtab, symtab, @intCast(address))) |sym| {
        try symbols.append(symbol_allocator, sym);
        return;
    }

    if (address >= si.runtime_virtual_base) {
        const relative_address = address - si.runtime_virtual_base;
        if (si.findSymbol(strtab, symtab, @intCast(relative_address))) |sym| {
            try symbols.append(symbol_allocator, sym);
            return;
        }
    }

    return error.MissingDebugInfo;
}

pub fn getModuleName(si: *SelfInfo, io: Io, address: usize) SelfInfoError![]const u8 {
    _ = io;
    try si.ensureParsed();
    if (address < si.runtime_virtual_base) return error.MissingDebugInfo;
    return "kernel";
}

pub fn getModuleSlide(si: *SelfInfo, io: Io, address: usize) SelfInfoError!usize {
    _ = io;
    _ = address;
    try si.ensureParsed();
    return si.runtime_virtual_base;
}

fn ensureParsed(si: *SelfInfo) SelfInfoError!void {
    switch (si.state) {
        .ready => return,
        .failed => |err| return err,
        .uninitialized => {},
    }

    si.initFromLimine() catch |err| {
        si.state = .{ .failed = err };
        return err;
    };
    si.state = .ready;
}

fn initFromLimine(si: *SelfInfo) SelfInfoError!void {
    const file_response = root.executable_file.response orelse return error.MissingDebugInfo;
    const executable_file = file_response.executable_file;
    const file_address = executable_file.address orelse return error.MissingDebugInfo;
    const file_size: usize = std.math.cast(usize, executable_file.size) orelse return error.InvalidDebugInfo;

    const addr_response = root.executable_address.response orelse return error.MissingDebugInfo;
    si.runtime_virtual_base = std.math.cast(usize, addr_response.virtual_base) orelse return error.InvalidDebugInfo;

    const file_ptr: [*]const u8 = @ptrCast(file_address);
    si.elf_bytes = file_ptr[0..file_size];

    var reader: std.Io.Reader = .fixed(si.elf_bytes);
    const header = elf.Header.read(&reader) catch |err| switch (err) {
        error.ReadFailed => unreachable,
        error.EndOfStream => return error.InvalidDebugInfo,
        error.InvalidElfMagic,
        error.InvalidElfVersion,
        error.InvalidElfClass,
        error.InvalidElfEndian,
        => return error.InvalidDebugInfo,
    };

    si.elf_is_64 = header.is_64;
    si.elf_endian = header.endian;

    const shstrtab = try getSectionStringTable(si.elf_bytes, &header);

    var it = header.iterateSectionHeadersBuffer(si.elf_bytes);
    var dwarf_sections: Dwarf.SectionArray = @splat(null);

    while (it.next() catch return error.InvalidDebugInfo) |shdr| {
        if (shdr.sh_type == elf.SHT_NULL or shdr.sh_type == elf.SHT_NOBITS) continue;
        if (shdr.sh_name >= shstrtab.len) return error.InvalidDebugInfo;

        const name = std.mem.sliceTo(shstrtab[@intCast(shdr.sh_name)..], 0);
        const section_bytes = try getSectionBytes(si.elf_bytes, shdr.sh_offset, shdr.sh_size);

        if (std.mem.eql(u8, name, ".symtab")) {
            si.symtab = .{
                .entry_size = shdr.sh_entsize,
                .bytes = section_bytes,
            };
        } else if (std.mem.eql(u8, name, ".strtab")) {
            si.strtab = section_bytes;
        }

        inline for (@typeInfo(Dwarf.Section.Id).@"enum".fields) |field| {
            if (std.mem.eql(u8, name, "." ++ field.name)) {
                dwarf_sections[field.value] = .{
                    .data = section_bytes,
                    .owned = false,
                };
            }
        }
    }

    if (si.symtab == null or si.strtab == null) return error.MissingDebugInfo;

    if (dwarf_sections[@intFromEnum(Dwarf.Section.Id.debug_info)] != null and
        dwarf_sections[@intFromEnum(Dwarf.Section.Id.debug_abbrev)] != null and
        dwarf_sections[@intFromEnum(Dwarf.Section.Id.debug_str)] != null and
        dwarf_sections[@intFromEnum(Dwarf.Section.Id.debug_line)] != null)
    {
        var dwarf: Dwarf = .{ .sections = dwarf_sections };
        const gpa = std.debug.getDebugInfoAllocator();
        dwarf.open(gpa, si.elf_endian) catch |err| switch (err) {
            error.InvalidDebugInfo,
            error.MissingDebugInfo,
            error.OutOfMemory,
            => |e| return e,
            error.EndOfStream,
            error.Overflow,
            error.ReadFailed,
            error.StreamTooLong,
            => return error.InvalidDebugInfo,
        };
        si.dwarf = dwarf;
    }
}

fn getSectionStringTable(bytes: []const u8, header: *const elf.Header) SelfInfoError![]const u8 {
    const shdr_offset = std.math.add(u64, header.shoff, std.math.mul(u64, header.shstrndx, header.shentsize) catch return error.InvalidDebugInfo) catch return error.InvalidDebugInfo;

    var reader: std.Io.Reader = .fixed(bytes);
    reader.seek = std.math.cast(usize, shdr_offset) orelse return error.InvalidDebugInfo;

    if (header.is_64) {
        const shdr = reader.takeStruct(elf.Elf64_Shdr, header.endian) catch return error.InvalidDebugInfo;
        return getSectionBytes(bytes, shdr.sh_offset, shdr.sh_size);
    } else {
        const shdr = reader.takeStruct(elf.Elf32_Shdr, header.endian) catch return error.InvalidDebugInfo;
        return getSectionBytes(bytes, shdr.sh_offset, shdr.sh_size);
    }
}

fn getSectionBytes(bytes: []const u8, offset: u64, size: u64) SelfInfoError![]const u8 {
    const start: usize = std.math.cast(usize, offset) orelse return error.InvalidDebugInfo;
    const len: usize = std.math.cast(usize, size) orelse return error.InvalidDebugInfo;
    const end = std.math.add(usize, start, len) catch return error.InvalidDebugInfo;
    if (end > bytes.len) return error.InvalidDebugInfo;
    return bytes[start..end];
}

fn tryDwarfGetSymbols(
    si: *SelfInfo,
    dwarf: *Dwarf,
    symbol_allocator: Allocator,
    text_arena: Allocator,
    address: usize,
    include_inline_callers: bool,
    symbols: *std.ArrayList(Symbol),
) bool {
    dwarf.getSymbols(
        symbol_allocator,
        text_arena,
        si.elf_endian,
        address,
        include_inline_callers,
        symbols,
    ) catch {};
    if (symbols.items.len != 0) return true;

    if (address >= si.runtime_virtual_base) {
        dwarf.getSymbols(
            symbol_allocator,
            text_arena,
            si.elf_endian,
            address - si.runtime_virtual_base,
            include_inline_callers,
            symbols,
        ) catch {};
        if (symbols.items.len != 0) return true;
    }

    return false;
}

fn findSymbol(si: *SelfInfo, strtab: []const u8, symtab: Symtab, target: u64) ?Symbol {
    if (symtab.entry_size == 0 or symtab.bytes.len % symtab.entry_size != 0) return null;

    const swap_endian = si.elf_endian != builtin.cpu.arch.endian();

    if (si.elf_is_64) {
        if (symtab.entry_size != @sizeOf(elf.Elf64_Sym)) return null;
        const symbols: []align(1) const elf.Elf64_Sym = @ptrCast(symtab.bytes);
        return findSymbolInTable(elf.Elf64_Sym, symbols, strtab, target, swap_endian);
    } else {
        if (symtab.entry_size != @sizeOf(elf.Elf32_Sym)) return null;
        const symbols: []align(1) const elf.Elf32_Sym = @ptrCast(symtab.bytes);
        return findSymbolInTable(elf.Elf32_Sym, symbols, strtab, target, swap_endian);
    }
}

fn findSymbolInTable(comptime Sym: type, symbols: []align(1) const Sym, strtab: []const u8, target: u64, swap_endian: bool) ?Symbol {
    var best_func: ?SymbolMatch = null;
    var best_any: ?SymbolMatch = null;

    for (symbols) |sym_orig| {
        var sym = sym_orig;
        if (swap_endian) std.mem.byteSwapAllFields(Sym, &sym);

        if (sym.st_name == 0) continue;
        if (sym.st_shndx == elf.SHN_UNDEF) continue;
        if (sym.st_size == 0) continue;
        if (sym.st_name >= strtab.len) continue;

        const start: u64 = sym.st_value;
        const end = std.math.add(u64, start, sym.st_size) catch continue;
        if (target < start or target >= end) continue;

        const candidate: SymbolMatch = .{
            .symbol = .{
                .name = std.mem.sliceTo(strtab[sym.st_name..], 0),
                .compile_unit_name = null,
                .source_location = null,
            },
            .start = start,
            .size = sym.st_size,
        };

        const sym_type = sym.st_info & 0x0f;
        if (sym_type == elf.STT_FUNC) {
            if (best_func == null or betterMatch(candidate, best_func.?)) best_func = candidate;
        } else {
            if (best_any == null or betterMatch(candidate, best_any.?)) best_any = candidate;
        }
    }

    if (best_func) |m| return m.symbol;
    if (best_any) |m| return m.symbol;
    return null;
}

const SymbolMatch = struct {
    symbol: Symbol,
    start: u64,
    size: u64,
};

fn betterMatch(new: SymbolMatch, old: SymbolMatch) bool {
    if (new.start > old.start) return true;
    if (new.start < old.start) return false;
    return new.size < old.size;
}
